CREATE TABLE IF NOT EXISTS parcours_reviews (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    parcours_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    rating TINYINT UNSIGNED NOT NULL,
    comment TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_review (parcours_id, user_id),
    INDEX idx_reviews_parcours (parcours_id),
    CONSTRAINT fk_reviews_parcours FOREIGN KEY (parcours_id) REFERENCES parcours(id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
